name: shell commands

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: echo name
        run: echo "hello world"
      - name: show version
        run: |
          node -v
          npm -v
  run-window:
    runs-on: windows-latest
    steps:
      - name: use bash shell
        run: pwd
        shell: bash
      - name: use Power shell
        run: Get-Location
